// Bundles skills/*/SKILL.md, knowledge/*.md and prompts/*.md into a TypeScript
// module so route handlers can import them without filesystem access at runtime
// (serverless bundles don't ship arbitrary files unless traced).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function parseFrontmatter(raw) {
  const text = raw.replace(/\r\n/g, "\n");
  const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { meta: {}, body: text.trim() };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx > 0) meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { meta, body: match[2].trim() };
}

const skillsDir = path.join(root, "skills");
const skills = fs
  .readdirSync(skillsDir)
  .filter((d) => fs.existsSync(path.join(skillsDir, d, "SKILL.md")))
  .sort()
  .map((dir) => {
    const { meta, body } = parseFrontmatter(fs.readFileSync(path.join(skillsDir, dir, "SKILL.md"), "utf8"));
    if (!meta.name || !meta.description) throw new Error(`skills/${dir}/SKILL.md needs name + description frontmatter`);
    return { name: meta.name, description: meta.description, body, path: `skills/${dir}/SKILL.md` };
  });

const knowledgeDir = path.join(root, "knowledge");
const knowledge = fs
  .readdirSync(knowledgeDir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((file) => {
    const { meta, body } = parseFrontmatter(fs.readFileSync(path.join(knowledgeDir, file), "utf8"));
    return { id: file.replace(/\.md$/, ""), title: meta.title ?? file, source: meta.source ?? "", body };
  });

const systemPrompt = fs.readFileSync(path.join(root, "prompts", "system.md"), "utf8").replace(/\r\n/g, "\n").trim();

const out = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit. Edit skills/, knowledge/ or prompts/ instead.
export const SKILLS = ${JSON.stringify(skills, null, 2)} as const;
export const KNOWLEDGE = ${JSON.stringify(knowledge, null, 2)} as const;
export const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
`;

fs.mkdirSync(path.join(root, "lib", "generated"), { recursive: true });
fs.writeFileSync(path.join(root, "lib", "generated", "content.ts"), out);
console.log(`content: ${skills.length} skills, ${knowledge.length} knowledge docs`);
